schema: S000001
driver: postgres
data_source_name: postgres://postgres:postgres@localhost:5432/example?sslmode=disable
table_schema_name: public
using_table_schema_name: true
column_serial: id
column_created_at: created_at,add_at
column_updated_at: updated_at,mod_at
column_deleted_at: deleted_at,del_at
package_model: model
template_output_directory: db
disable_table_name_match_rules:
    - ^aaa_.*$
    - ^.*_zzz$
allow_table_name: []
allow_table_name_match_rules: []
api_echo: false
import_prefix: github.com/cd365/hey-example/db
import_prefix_abc: github.com/cd365/hey-example/db
